[package]
name = "kyber"
version = "0.1.0"
authors = ["Mitchell <17392435+MitchellBerry@users.noreply.github.com>"]
edition = "2018"


[dependencies]
rand = "0.7.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "api"
harness = false

# Will throw a compile_error if more than one security level is chosen
# "kyber764" is the default if no other security level is specified
# As a feature it has no effect yet is made available for end-user clarity
[features]
# Security Levels
kyber512 = []
kyber764 = []
kyber1024 =[]
kyber512-90s = []
kyber764-90s = []
kyber1024-90s = []

# Additional features
avx2 = []
wasm = []

# Verification Testing
# Allows access to private api functions to seed the RNG output 
# Do not use for any purpose other than running the Known Answer Tests
KATs = []