[package]
name = "kyber"
version = "0.1.0"
authors = ["Mitchell <17392435+MitchellBerry@users.noreply.github.com>"]
edition = "2018"


[dependencies]
rand = { version = "0.7.3", features =["wasm-bindgen"]}
wasm-bindgen = { version = "0.2.67", optional = true}

[dev-dependencies]
criterion = "0.3"

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "api"
harness = false

# Will throw a compile_error if more than one security level is chosen
# "kyber764" is the default if no other security level is specified
# As a feature it has no effect yet is made available for end-user clarity
[features]
# Security Levels
kyber512 = []
kyber764 = []
kyber1024 =[]
kyber512-90s = ["90s"]
kyber764-90s = ["90s"]
kyber1024-90s = ["90s"]

# Additional features
avx2 = []
wasm = ["wasm-bindgen"]


# Verification Testing
# Allows access to private api functions to seed the RNG output 
# Do not use for any purpose other than running the Known Answer Tests
KATs = []

# Internal conditional flag
90s = []