[package]
name = "pqc-kyber"
version = "0.1.0"
authors = ["Mitchell Berry <17392435+MitchellBerry@users.noreply.github.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/MitchellBerry/kyber"
documentation = "https://docs.rs/crate/pqc-kyber/"
categories = ["algorithms", "cryptography"]
description = "A pure rust implementation of the Kyber algorithm"
keywords = ["cryptography", "kyber", "kem", "key exchange", "post-quantum"]
readme = "readme.md"

[dependencies]
rand_core = "0.5.1"
rand = { version = "0.7.3", features =["wasm-bindgen"]}
wasm-bindgen = { version = "0.2.67", optional = true}

[dev-dependencies]
criterion = "0.3"

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "api"
harness = false

[features]
# Security Levels
# Will throw a compile_error if more than one level is chosen
# "kyber764" is the default if none is specified
kyber512 = []
kyber764 = []
kyber1024 =[]

# Additional features
avx2 = []
wasm = ["wasm-bindgen"]


# Verification Testing
# Allows access to private api functions to seed the RNG output 
# Do not use for any purpose other than running the Known Answer Tests
KATs = []