name: All-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ development ]

jobs:
  all-tests:
    name: Test Matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Generate KATs
        shell: bash
        working-directory: ./tests/KATs
        run: |
          chmod +x build_kats.sh
          bash build_kats.sh

      - name: Run tests on all features
        shell: bash
        working-directory: ./tests
        run: |
          chmod +x run_all_tests.sh
          bash run_all_tests.sh